--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Frost-Creations/FCAuctionHouse
build-by-default: true
branches:
- main
projects: 
  FCAuctionHouse:
    path: ""
    lint: false
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
      - src: muqsit/invmenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
      - src: CortexPE/Commando/Commando
        version: ^3.2.0
        branch: master
...
